name: meta preview
on: { pull_request: { paths: ["meta/drafts/**"] } }
jobs:
  preview:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: meta } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: pnpm i && pnpm run build
      - run: node dist/cli.js drafts/*.md dry-run
      - uses: actions/upload-artifact@v4
        with: { name: meta-dist, path: meta/dist }
