name: pre-commit
on: [push, pull_request]
jobs:
  pc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - uses: pre-commit/action@v3.0.1
