name: reuse-shared-docs
on:
  push:
    branches: [ main ]
    paths: ['docs/**','.github/workflows/reuse-docs.yml']
  workflow_dispatch: {}
jobs:
  call:
    uses: VaultSovereign/Vm-umbrella/.github/workflows/shared-docs.yml@v0.4.0
